# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: dotnet build Jasper.sln
  displayName: 'Compile Everything'

- script: dotnet test src/Jasper.Testing/Jasper.Testing.csproj --no-restore
  displayName: 'Unit Tests'

- script: dotnet test src/Jasper.TestSupport.Tests/Jasper.TestSupport.Tests.csproj --no-restore
  displayName: 'TestSupport Unit Tests'
